# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkMemes-aula24.08' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4'

  target 'NetworkMemes-aula24.08Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkMemes-aula24.08UITests' do
    # Pods for testing
  end

end
